# Generated by Django 5.1.7 on 2025-04-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo_alter_cor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor'},
        ),
    ]
